version: '3'
services:
    django:
        image: django
        env_file: default.env
        hostname: "${HOSTNAME}"
        container_name: "${PROJECT_NAME}"
        ports:
            - 5000:5000
        volumes:
            - "./src:/usr/src"
        working_dir: /usr/src
        command: apt-get update
        command: apt-get install -y --no-install-recommends postgresql-client
        command: rm -rf /var/lib/apt/lists/*
        command: pip install -r requirements.txt
        command: python manage.py runserver 0.0.0.0:5000
    db:
      image: postgres:latest
      environment:
        POSTGRES_DB: be_free_db
        POSTGRES_PASSWORD: 4lb3r272
        POSTGRES_USER: jaja-laja
      ports:
        - 4000:4000
