#!/bin/bash

#esc="^[" 
esc="\033"
black="${esc}[30m"
red="${esc}[31m"
green="${esc}[32m"
yellow="${esc}[33m"
blue="${esc}[34m"
pink="${esc}[35m"
cyan="${esc}[36m"
white="${esc}[37m"

f_black="${esc}[40m"
f_red="${esc}[41m"
f_verde="${esc}[42m"
f_yellow="${esc}[43m"
f_blue="${esc}[44m"
f_pink="${esc}[45m"
f_cyan="${esc}[46m"
f_white="${esc}[47m"

bold="${esc}[1m"
q_bold="${esc}[22m"
italic="${esc}[3m"
q_italic="${esc}[23m"
underline="${esc}[4m"
q_underline="${esc}[24m"
inverse="${esc}[7m"
q_inverse="${esc}[27m"

reset="${esc}[0m"
